### ISSUE TITLE
Any chance for getting a compiled version with VC redist lower than 2015?

### ISSUE THREAD

**Issue by Illasera** [nalexandru/BlenderCompat#10]
vcdist 2015 and above are for windows 7 SP1.

Any chance we can get a version that requires VCDist runlime lib with versions below 2015 as we used to?

as i recall correctly, you wrote something about changing visual studio version.

Any chance you can re-gain a copy of the older version and compile there as you did with blender 3.0?

(Yes, we can compile blender ourselves with an older visual studio but it will be a nightmare for anyone not used to compiling blender to get into it and start configuration everything and check dependencies and what not.

It would mean the world to me and anyone without Windows Service pack 1 for windows to get a version that works on windows 7 without service pack.

**Comment by nalexandru** [comment]
The build of Blender 3.0 that i uploaded was compiled with VS2019 and the betas / rc of 3.1 with VS2022.
The current master of Blender supports VS2019 and VS2022, so i don't know if it will build with an older version.
What i can do, is to build it with VS2019 (like the 3.0 and 3.0.1 releases i uploaded) as long as it's possible. I will upload 3.1.0 later today built with VS2019.

**Comment by nalexandru** [comment]
I've uploaded 3.1.0 built with VS2019 (same as 3.0.0 and 3.0.1). Can you check if it works ?

**Comment by Illasera** [comment]
sure mate, 

thank you, 

I just need to finish uploading every single .dll and .exe to virustotal and will give it a shot 
(No, it doesn't scan archives, or at least it doesn't handle them correctly)

so once all files are scanned, will give it a shot.

**Comment by nalexandru** [comment]
This list has all the library changes for 3.1: https://developer.blender.org/T93161
There haven't been any changes that required extra modifications from me for 3.1 or the current master, 3.2.0-fe3a9fcce1e6.

**Comment by Illasera** [comment]
@nalexandru I apologize, i wrote my reply when you asked me but seems like i didn't click the "Comment" reply

Yes, it works on windows 7, your blender  3.1 release. Thank you.

**Comment by nalexandru** [comment]
Ok, i will build it with 2019 for as long as it's possible then.

**Comment by Illasera** [comment]
> Ok, i will build it with 2019 for as long as it's possible then.

Thank you sir, You are doing god's work, I am a bit fearful when it comes to 3.2, I have noticed tons of libraries updates.

**Comment by nalexandru** [comment]
As of yesterday's master, 3.2.0 5387d33e5f95, there are no problems with the changes made (on Windows 7 with the May 2016 rollup).
