### ISSUE TITLE
Feeding Noise Texture Into Bump Map's Height Produces Error Pink Output

### ISSUE THREAD

**Issue by hkunz** [nalexandru/BlenderCompat#12]
Steps To Reproduce:

1. Open Blender **2.93**, **3.0** or **3.1** on Windows **7**
1. Go to **Shader Editor**
2. Add a **Noise Texture** node & a **Bump Map** node
3. Feed the Noise Texture's **Color** or **Fac** output into the Bump Map's **Height** input
4. Shift+CTRL+LMB on the Bump Map
5. Notice the output is pink

**Comment by nalexandru** [comment]
I was unable to follow your instructions exactly (probably due to my limited knowledge of Blender). Is what i did here correct ?

https://user-images.githubusercontent.com/9295849/163158732-fa7ee2fb-ebb2-4271-bb28-cd6b53d32afe.mp4

Shift+Click+LMB does nothing (other than selecting the node), so i connected the output of the Bump node to the Normal input and it seems to be working.

**Comment by hkunz** [comment]
hey thank you so much for looking into this. yeah what u did was correct. are u on windows 7? for me the result would be pink hmmmm i wonder why.

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 13, 2022 at 18:33, Alexandru ***@***.***> wrote:   


I was unable to follow your instructions exactly (probably due to my limited knowledge of Blender). Is what i did here correct ?

https://user-images.githubusercontent.com/9295849/163158732-fa7ee2fb-ebb2-4271-bb28-cd6b53d32afe.mp4

Shift+Click+LMB does nothing (other than selecting the node), so i connected the output of the Bump node to the Normal input and it seems to be working.

**Comment by hkunz** [comment]
PS: CTRL+SHIFT+<Left Mouse Button> on a node will show you the result for that node. it's like debugging technique to see each node output.

**Comment by hkunz** [comment]
i tried the new version 3.1.2 from your release page https://github.com/nalexandru/BlenderCompat/releases and i still get a pink result :( let me know if you are running on windows 7 as well coz that's where the problem occurs

**Comment by hkunz** [comment]
ah it keeps saying "Texture state usage warning: Texture 0 is base level inconsistent. Check texture size."

**Comment by hkunz** [comment]
INFO (gpu.debug): Notification : Texture state usage warning: Texture 0 is base level inconsistent. Check texture size.
INFO (gpu.debug): Notification : Rasterization usage warning: Blending is enabled, but is not supported for integer framebuffers.
ERROR (gpu.shader): GPU_material_compile Linking: 
      | Fragment info
      | -------------
      | Internal error: assembly compile error for fragment shader at offset 427508:
      | -- error message --
      | line 16649, column 1:  error: too many instructions
      | -- internal assembly text --
      | !!NVfp5.0
      | OPTION NV_gpu_program_fp64;
      | OPTION NV_bindless_texture;
      | OPTION NV_shader_atomic_float;
      | OPTION ARB_draw_buffers;
      | OPTION ARB_fragment_program_shadow;
      | # cgc version 3.4.0001, build date Sep 13 2014
      | # command line args: 
      | #vendor NVIDIA Corporation
      | #version 3.4.0.1
      | #profile gp5fp
      | #program main
      | #semantic viewBlock : BUFFER[0]
      | #semantic modelBlock : BUFFER[1]
      | #semantic common_block : BUFFER[2]
      | #semantic renderpass_block : BUFFER[3]
      | #semantic probe_block : BUFFER[4]
      | #semantic grid_block : BUFFER[5]
      | #semantic planar_block : BUFFER[6]
      | #semantic shadow_block : BUFFER[7]
      | #semantic light_block : BUFFER[8]
      | #semantic nodeTree : BUFFER[9]
      | #semantic hairStrandsRes
      | #semantic hairThicknessRes
      | #semantic hairRadRoot
      | #semantic hairRadTip
      | #semantic hairRadShape
      | #semantic hairCloseTip
      | #semantic hairDupliMatrix
      | #semantic hairStrandOffset
      | #semantic hairPointBuffer
      | #semantic hairStrandBuffer
      | #semantic hairStrandSegBuffer
      | #semantic drw_resourceChunk
      | #semantic utilTex
      | #semantic maxzBuffer
      | #semantic planarDepth
      | #semantic horizonBuffer
      | #semantic irradianceGrid
      | #semantic probePlanars
      | #semantic probeCubes
      | #semantic shadowCubeTexture
      | #semantic shadowCascadeTexture
      | #semantic inScattering
      | #semantic inTransmittance
      | #semantic refractColorBuffer
      | #semantic refractionDepth
      | #semantic outputSsrId
      | #semantic outputSssId
      | #var float gl_FrontFacing : $vin.FACE : SSA : -1 : 1
      | #var float4 gl_FragCoord : $vin.WPOS : WPOS : -1 : 1
      | #var float4x4 ViewProjectionMatrix : BUFFER[0] : buffer[0][0], 4 : -1 : 1
      | #var float4x4 ViewProjectionMatrixInverse : BUFFER[0] : buffer[0][64], 4 : -1 : 0
      | #var float4x4 ViewMatrix : BUFFER[0] : buffer[0][128], 4 : -1 : 1
      | #var float4x4 ViewMatrixInverse : BUFFER[0] : buffer[0][192], 4 : -1 : 1
      | #var float4x4 ProjectionMatrix : BUFFER[0] : buffer[0][256], 4 : -1 : 1
      | #var float4x4 ProjectionMatrixInverse : BUFFER[0] : buffer[0][320], 4 : -1 : 0
      | #var float4 clipPlanes[0] :  : buffer[0][384] : -1 : 0
      | #var float4 ViewVecs[0] :  : buffer[0][480] : -1 : 1
      | #var float4 CameraTexCoFactors : BUFFER[0] : buffer[0][512] : -1 : 0
      | #var float4x4 drw_matrices[0].drw_modelMatrix :  : buffer[1][0], 4 : -1 : 0
      | #var float4x4 drw_matrices[0].drw_modelMatrixInverse :  : buffer[1][64], 4 : -1 : 0
      | #var float4x4 pastViewProjectionMatrix : BUFFER[2] : buffer[2][0], 4 : -1 : 0
      | #var float4 hizUvScale : BUFFER[2] : buffer[2][64] : -1 : 1
      | #var float4 aoParameters[0] :  : buffer[2][80] : -1 : 1
      | #var int4 volTexSize : BUFFER[2] : buffer[2][112] : -1 : 0
      | #var float4 volDepthParameters : BUFFER[2] : buffer[2][128] : -1 : 0
      | #var float4 volInvTexSize : BUFFER[2] : buffer[2][144] : -1 : 0
      | #var float4 volJitter : BUFFER[2] : buffer[2][160] : -1 : 0
      | #var float4 volCoordScale : BUFFER[2] : buffer[2][176] : -1 : 0
      | #var float volHistoryAlpha : BUFFER[2] : buffer[2][192] : -1 : 0
      | #var float volShadowSteps : BUFFER[2] : buffer[2][196] : -1 : 0
      | #var bool volUseLights : BUFFER[2] : buffer[2][200] : -1 : 0
      | #var bool volUseSoftShadows : BUFFER[2] : buffer[2][204] : -1 : 0
      | #var float4 ssrParameters : BUFFER[2] : buffer[2][208] : -1 : 1
      | #var float ssrBorderFac : BUFFER[2] : buffer[2][224] : -1 : 0
      | #var float ssrMaxRoughness : BUFFER[2] : buffer[2][228] : -1 : 0
      | #var float ssrFireflyFac : BUFFER[2] : buffer[2][232] : -1 : 0
      | #var float ssrBrdfBias : BUFFER[2] : buffer[2][236] : -1 : 0
      | #var bool ssrToggle : BUFFER[2] : buffer[2][240] : -1 : 1
      | #var bool ssrefractToggle : BUFFER[2] : buffer[2][244] : -1 : 0
      | #var float sssJitterThreshold : BUFFER[2] : buffer[2][248] : -1 : 0
      | #var bool sssToggle : BUFFER[2] : buffer[2][252] : -1 : 0
      | #var bool specToggle : BUFFER[2] : buffer[2][256] : -1 : 1
      | #var int laNumLight : BUFFER[2] : buffer[2][260] : -1 : 1
      | #var int prbNumPlanar : BUFFER[2] : buffer[2][264] : -1 : 1
      | #var int prbNumRenderCube : BUFFER[2] : buffer[2][268] : -1 : 1
      | #var int prbNumRenderGrid : BUFFER[2] : buffer[2][272] : -1 : 1
      | #var int prbIrradianceVisSize : BUFFER[2] : buffer[2][276] : -1 : 1
      | #var float prbIrradianceSmooth : BUFFER[2] : buffer[2][280] : -1 : 1
      | #var float prbLodCubeMax : BUFFER[2] : buffer[2][284] : -1 : 1
      | #var int rayType : BUFFER[2] : buffer[2][288] : -1 : 0
      | #var float rayDepth : BUFFER[2] : buffer[2][292] : -1 : 0
      | #var float alphaHashOffset : BUFFER[2] : buffer[2][296] : -1 : 0
      | #var float alphaHashScale : BUFFER[2] : buffer[2][300] : -1 : 0
      | #var float pad6 : BUFFER[2] : buffer[2][304] : -1 : 0
      | #var float pad7 : BUFFER[2] : buffer[2][308] : -1 : 0
      | #var float pad8 : BUFFER[2] : buffer[2][312] : -1 : 0
      | #var float pad9 : BUFFER[2] : buffer[2][316] : -1 : 0
      | #var bool renderPassDiffuse : BUFFER[3] : buffer[3][0] : -1 : 1
      | #var bool renderPassDiffuseLight : BUFFER[3] : buffer[3][4] : -1 : 1
      | #var bool renderPassGlossy : BUFFER[3] : buffer[3][8] : -1 : 1
      | #var bool renderPassGlossyLight : BUFFER[3] : buffer[3][12] : -1 : 1

INFO (gpu.debug): Notification : Texture state usage warning: Texture 0 is base level inconsistent. Check texture size.

**Comment by nalexandru** [comment]
That warning appears in my log too so i don't think it has anything to do with the issue.
There is a shader compilation error on line 455 of blender_debug_output.txt:
ERROR (gpu.shader): GPU_material_compile Linking: 
      | Fragment info
      | -------------
      | Internal error: assembly compile error for fragment shader at offset 427508:
      | -- error message --
      | line 16649, column 1:  error: too many instructions

I see from the system info that you have a GTX TITAN with driver version 344.11:
renderer:	'GeForce GTX TITAN/PCIe/SSE2'
vendor:		'NVIDIA Corporation'
version:	'4.4.0 NVIDIA 344.11'

Try updating the GPU driver to the latest version (and probably last) for Windows 7 which is 473.04 and can be found here: https://www.nvidia.com/en-gb/drivers/results/186161/

**Comment by hkunz** [comment]
yeah saw it now too

**Comment by hkunz** [comment]
oh nooo i get error when installing the update https://pasteall.org/pic/592d51cd44b14c2c932e4bf20eb86e15 :(

**Comment by hkunz** [comment]
thank you very much for your time and help i really appreciate it! and i did give you credits in my video on "how to install blender 3.1 on windows 7 :) https://www.youtube.com/watch?v=n3RGmnRTig8
