### ISSUE TITLE
Eevee materials not working starting from 3.2.0 beta 967f96ee2e2e

### ISSUE THREAD

**Issue by FyiurAmron** [nalexandru/BlenderCompat#18]
Neither the preview (shows black box for everything apart from hair) not the actual rendering works for me anymore. It still works in 3.2.0 beta bf352df27a6f. Hard to say if it's related to core blender code, or Win7 compat. A wild guess, but maybe 3.2.1 fixed it somehow already?

**Comment by nalexandru** [comment]
I will upload 3.2.1 in a few hours.

I doubt it's related to the compat layer because there were no changes since [3.2.0 beta cbc024c3cac2](https://github.com/nalexandru/BlenderCompat/releases/tag/3.2.0-beta.3-cbc024c3cac2) and it doesn't do anything for graphics.

Try running Blender with "blender_debug_gpu.cmd" instead of "blender.exe", go the the preview and exit. After Blender closes, it will open a folder with two files, "blender_debug_output.txt" and "blender_system_info.txt".
Please upload those 2 files.

**Comment by FyiurAmron** [comment]
Yeah, they are, I guess there's basically nothing to log since I can verify it happens as soon as Blender is launched without doing virtually anything. Still, the bugs you found seem basically exactly like the one I have, so I guess it's 99% unrelated to Win7 compatibility itself. I've checked 3.2.1, it still happens, although in fact it's an Eevee-only bug - Cycles & Workbench still work perfectly. I'll close it here and try reporting it on Blender's tracker, though I honestly suspect they'll close the report due to Win7 being unsupported, even if (which I suspect) the bug is reproducible on *n*x, MacOs and Win10 :D

BTW thanks for the info on the drivers - I've stopped checking some time ago after AMD said they're dropping support for Win7 drivers, and I'm quite surprised they shipped some as late as April/May 2022'. They don't seem to help though, but it's good to have them updated anyway :}

**Comment by nalexandru** [comment]
I was unable to reproduce this issue on a RX550 on Win7 with 21.5.2 or 22.6.1.

**Comment by nalexandru** [comment]
@FyiurAmron there has been another rendering issue on an RX580, #19, which was fixed by this build: https://1drv.ms/u/s!AhpnXywMA4U1mUYW4jtP0GsxlPHF. Can you test if it fixes this as well ?

**Comment by FyiurAmron** [comment]
@nalexandru what can I say? KUDOS :bow: :bow: :bow: :+1: :100: - it seems that https://developer.blender.org/rBd1340e1bb250f6ec4b9781f4b9c5f01a9e4da9e9 was indeed the thing here, it works perfectly again now!

**Comment by nalexandru** [comment]
I'm not surprised by their response.
I will include it and when 3.2.2 releases it will be applied.

The reason i was unable to reproduce this on my RX550 is that the workaround was left enabled for it. It seems AMD's drivers are not identical on 7 and 10, the same driver version (tested 22.6.1) is missing a few Vulkan extensions on 7, so i assume they've fixed the driver bug mentioned in that commit only in the Win10 version.
