### ISSUE TITLE
View Shading bug

### ISSUE THREAD

**Issue by lnesuper** [nalexandru/BlenderCompat#19]
3.2 View Shading:
Material Preview and Rendered 
 The view shows only the model boundary (yellow border) 
3.2.1 View Shading:  The same problem 
but Render Engine with cycles, The view Shading is ok.

**Comment by nalexandru** [comment]
Run Blender with "blender_debug_gpu.cmd" instead of "blender.exe", go the the preview / do a render and exit. After Blender closes, it will open a folder with two files, "blender_debug_output.txt" and "blender_system_info.txt".
Please upload those 2 files.

**Comment by lnesuper** [comment]
[https://wwc.lanzouq.com/i2rB207r0bcd](url)

**Comment by lnesuper** [comment]
But View Shading is normal until 3.1.2

**Comment by nalexandru** [comment]
The logs are empty and i see you are using an RX 580. This could be similar to #18 
Can you try [3.2.0 beta bf352df27a6f](https://github.com/nalexandru/BlenderCompat/releases/tag/3.2.0-beta.4-bf352df27a6f) and see if the problem exists in that version ?

**Comment by lnesuper** [comment]
> The logs are empty and i see you are using an RX 580. This could be similar to #18 Can you try [3.2.0 beta bf352df27a6f](https://github.com/nalexandru/BlenderCompat/releases/tag/3.2.0-beta.4-bf352df27a6f) and see if the problem exists in that version ?

this version is normal.

**Comment by lnesuper** [comment]
84e55e3dc251-may-22 normal
bdab538b3019-may-23 normal
[blender.zip](https://github.com/nalexandru/BlenderCompat/files/9135659/blender.zip)

**Comment by nalexandru** [comment]
I believe the cause of the problem is this: https://developer.blender.org/rBd1340e1bb250f6ec4b9781f4b9c5f01a9e4da9e9.
I've made a build with that commit reverted: https://1drv.ms/u/s!AhpnXywMA4U1mUYW4jtP0GsxlPHF. Let me know if it works.

**Comment by lnesuper** [comment]
> I believe the cause of the problem is this: https://developer.blender.org/rBd1340e1bb250f6ec4b9781f4b9c5f01a9e4da9e9. I've made a build with that commit reverted: https://1drv.ms/u/s!AhpnXywMA4U1mUYW4jtP0GsxlPHF. Let me know if it works.

It works normal.
[debug_logs.zip](https://github.com/nalexandru/BlenderCompat/files/9137303/debug_logs.zip)

**Comment by nalexandru** [comment]
I've integrated the reversal of the commit in the patch. Blender 3.2.2 and all subsequent releases will have the commit reverted and should render correctly on AMD Polaris GPUs.
