### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by patientAtGithub** [nalexandru/BlenderCompat#21]
Sorry for the "noise". I just wanted to find a way to say thank you for compiling these windows7 compatible binaries of blender. I truly appreciate it. I was trying to find a way to contact you and tell you mulţumesc!

**Comment by Kieruss** [comment]
Yes, thank you very much. You're awesome :trophy: :smiling_face_with_tear:

**Comment by nalexandru** [comment]
You're welcome.
