### ISSUE TITLE
Render Farms

### ISSUE THREAD

**Issue by Abubaqar** [nalexandru/BlenderCompat#24]
Thankyou very much for your hardwork I appreciate it, but There's a Issue with importing addons for renderfarms like Polargrid, RenderBeamer (Garage Farm) etc.
Please try to fix this ASAP It's very Important for me,
Thankyou again for making it possible to run Blender on my old PC.

**Comment by nalexandru** [comment]
Please provide more information about the problem, what is the error you are getting ?

**Comment by Abubaqar** [comment]
![-6192614788496994630_121](https://user-images.githubusercontent.com/76098129/194293965-4d8d7b9f-36ad-4f89-b577-2fe562584b41.jpg)
Check this please

**Comment by nalexandru** [comment]
It seems to fail when loading the socket library, i can't reproduce this from the python console. Can you upload the renderbeamer addon zip ? I wasn't able to find a download link for it.
The other one you mentioned, Polargrid (i assume this is it: https://polargrid.space), installs without any issues for me.

Have you installed all Windows updates (up to January 2020) ? In addition to Windows updates, try updating the Visual C++ runtime (download link: https://aka.ms/vs/17/release/vc_redist.x64.exe).

**Comment by Abubaqar** [comment]
https://garagefarm.net/blender-render-farm

it's the Link for RenderBeamer (Gives 50$ Render Credits Which Lasts Long enoungh for me)

I updated my Windows and also Installed Visual C++ But Still it shows the same Error.
It will be Ok if there's no Solution for it as I already tried some DifferentMethods Which Works, But having the render farm directly in Blender is Best. So I'm hoping for a Good Permanent Solution
Thankyou for your Quick replies

**Comment by Abubaqar** [comment]
It worked, Thankyou very very much for your Help.
