### ISSUE TITLE
V3.4, Asian characters look terrible when anti-aliasing is off.

### ISSUE THREAD

**Issue by LD-531** [nalexandru/BlenderCompat#28]
W7 x64
Blender V3.4

![see](https://user-images.githubusercontent.com/58158624/206891360-a5131f7e-1d1d-4b7e-968b-721c33b19cd4.png)

**Comment by nalexandru** [comment]
I've found a potential solution until upstream fixes it, which is to use a different interface font.
The image below is using Source Han Serif (https://github.com/adobe-fonts/source-han-serif):

![w7_shs](https://user-images.githubusercontent.com/9295849/206907688-2faddbc2-cee4-40cb-ac3a-cf4e1bf03a0a.PNG)

**Comment by LD-531** [comment]
This issue has been fixed in V4.x.
