### ISSUE TITLE
The geometry-nodes-simulation brunch

### ISSUE THREAD

**Issue by newillusion** [nalexandru/BlenderCompat#38]
Huge thanks to You, Alexandru Naiman for prolongate life of our OS and, indirectly, us!

On "blender.org" is official brunch "geometry-nodes-simulation", it's contains very important technics, extend geomentry nodes of Blender to power like Houdini.

But, i think, it brunch will not be implemented to main Blender brunch and this technics will not be accessible for us.

Is it possible to make build "geometry-nodes-simulation" for Win7?

**Comment by nalexandru** [comment]
That branch is for a feature that is not yet finished. It will be merged when it is complete.

I've compiled it, you can find it here: https://1drv.ms/u/s!AhpnXywMA4U1mXkjvIxNWeJaOADK?e=jZiZXj.

**Comment by newillusion** [comment]
It's works great! Everlasting gratitude to You!

> > It will be merged when it is complete.

I saw a lot of great and usefull, great beginnings, what not was merged in Blender. For example, paricle nodes, and so on...
