### ISSUE TITLE
Asset browser freezing and do not save assets

### ISSUE THREAD

**Issue by waltage80** [nalexandru/BlenderCompat#4]
Asset browser freezing and do not save assets
folders do not save on disc
![image](https://user-images.githubusercontent.com/42547770/145380083-84c9b78b-f72e-4c7c-b374-d60092877903.png)

**Comment by nalexandru** [comment]
I am unable to reproduce the freeze, can you provide reproduction steps ? Is there an error message when saving the .blend file with the assets ?

As for the second part, i don't know what you mean with "folders do not save on disc". The asset catalog you created, "MESHES", is not a folder on disc, it is saved in the .blend file which you save in a directory that you added to the Asset Libraries paths (Edit > Preferences > File Paths > Asset Libraries)

**Comment by waltage80** [comment]
1 do not save NOTHING in Asset Libraries paths 
2 do not put asset in asset browser
3 do not bake only artifacts

**Comment by nalexandru** [comment]
I don't understand what you mean. You must save the .blend file in that directory, Blender won't save anything automatically. The assets are in the .blend file, not separate.
See [https://docs.blender.org/manual/en/latest/files/asset_libraries/introduction.html](https://docs.blender.org/manual/en/latest/files/asset_libraries/introduction.html).
