### ISSUE TITLE
Virus detections on blender-3.6.0-beta-370b7ae917-windows-7.zip

### ISSUE THREAD

**Issue by newillusion** [nalexandru/BlenderCompat#45]
There is 4 virus detections on blender-3.6.0-beta-370b7ae917-windows-7.zip.

![Virus detection on Blender](https://github.com/nalexandru/BlenderCompat/assets/13040758/f777534c-92c0-48e3-8563-aa08adf1b2e8)

Previous version (blender-3.6.0-geometry-nodes-simulation-e665a50fb636-windows-7.zip) is clear. Original blender boundle (blender-3.6.0-beta+v36.92b4e7498596-windows.amd64-release) is clear too.

**Comment by nalexandru** [comment]
Please let me know what files inside the zip are flagged.

**Comment by newillusion** [comment]
That is not so easy, becouse VirusTotal.com not shows files individually, and testing ~6500 files one-by-one take so many time, what, i think, i waste more than one day for such work.
And now it is no sence, becouse next assebmly "blender-3.6.0-beta-e2a75814ac-windows-7.zip" is clear.

**Comment by nalexandru** [comment]
There were no changes in the build environment between 370b7ae917 and e2a75814ac. I think that the detections are false positives.

**Comment by Illasera** [comment]
Testing i made on 3.6.0 showed everything in the clear

"There is no way to test all files on virustotal"

correct, we drop every DLL and EXE by hand, it takes 5 minutes.

you don't scan all the files, just DLL and EXE files.
*Yes folks, malware can be executed by scripting language like python etc...
but no anti-virus will detect it anyway.
