### ISSUE TITLE
[Feature request] Please, make a upgrade alpha/beta Blender versions to Windows 7 too!

### ISSUE THREAD

**Issue by newillusion** [nalexandru/BlenderCompat#6]
Dear author! Thanks for the possibility to use last Blender release with last personal OS Windows 7!

And can You upgrade not only releases of Blender, but some new alpha/beta versions too? With the beta status (and alpha), this versions more stably than, for example, 3ds max release and it also can be used almost fully.

Thanks!

**Comment by nalexandru** [comment]
In alpha new features might be added that require additional work to support Windows 7. For this reason, i will not be making builds for alpha versions.

Once the new version is in beta, i will try to get it running on 7 and if possible i will be providing binaries as time permits.

**Comment by Loriem** [comment]
If Alexandru does not mind, I can provide a link where everyone can download the latest builds (not every day, of course), since I relatively often do rebuilds as new alpha, beta and RC 3.0.1 and 3.1 are released.

**Comment by nalexandru** [comment]
@Loriem Please do.

**Comment by Loriem** [comment]
Alexandru, thanks.
https://www.dropbox.com/sh/eufffe60fvtr9mz/AAA0YtogOoJTKggWtgAXRyXJa?dl=0
I've uploaded at the moment version 3.0.1 stable only.
Version 3.1 will be added when beta status. It will probably happen in the next few days.

**Comment by nalexandru** [comment]
Can i put your link in the readme ?

**Comment by Loriem** [comment]
Surely!

**Comment by nalexandru** [comment]
Thanks, i've updated the readme to include your link.
