### ISSUE TITLE
blender 4.0.2 does not compile with the Windows 8.1 SDK

### ISSUE THREAD

**Issue by gfernval** [nalexandru/BlenderCompat#73]
Hello:

Cannot compile blender 4.0.2 with Microsoft SDK 8.1 (the one that is compatible with windows 7), with SDK 10 compiles succesfully but the executable cannot run in Windows 7 due to "The procedure entry point GetPointerInfoHistory could not be located in the dynamic library USER32.dll", I use Visual Studio 2019 for compiling, any advices?

**Comment by gfernval** [comment]
git apply bcompat7.patch fails with:

error: patch failed: source/creator/CMakeLists.txt:1285
error: source/creator/CMakeLists.txt: patch does not apply

**Comment by nalexandru** [comment]
I've updated the patch. It should work now.
The patch lags behind, because i use git stash when updating the Blender source.

As stated in the release notes, i build Blender with Visual Studio 2019 and version 10.0.22621 of the Windows SDK (Windows 11 SDK, currently the latest version)

**Comment by gfernval** [comment]
Thanks, it works!
