### ISSUE TITLE
Can't install addon on Windows 7 x64. 

### ISSUE THREAD

**Issue by EtherealQuest** [nalexandru/BlenderCompat#78]
It says: 
"ImporError: DLL load failed while importing _multiarray_umath: The parameter is incorrect" 
and also says: 
"Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup of how NumPy was installed"

**Comment by nalexandru** [comment]
You need to have some updates installed for numpy to work, please see the discussion about 4.0.1,  https://github.com/nalexandru/BlenderCompat/discussions/71#discussioncomment-7763777

**Comment by nalexandru** [comment]
You're welcome.
