### ISSUE TITLE
4.2.0 alpha build

### ISSUE THREAD

**Issue by acyc070** [nalexandru/BlenderCompat#88]

**Comment by nalexandru** [comment]
The reason i don't make alpha builds is that there may be changes (which might need workarounds) that will not make it into the final release. Once a version reaches beta, the feature set is finalized.

If you don't have an AMD GPU, you can try installing the [Windows 7 Extended Kernel](https://github.com/vxiiduu/VxKex) and run the official binaries. It says in the project's readme that Blender is supported, but i haven't tried it.
